# Rolling nightly channel pointer, generated by .github/workflows/nightly.yml.
#
# This file lives on the `nightly` git ref, where its hash matches the
# artifact published in the current rolling nightly release:
#
#   nix run github:Ignis-lang/ignis/nightly#ignis-nightly
{
  version = "nightly-6c398730";

  artifacts = {
    "x86_64-linux" = {
      url = "https://github.com/Ignis-lang/ignis/releases/download/nightly/ignis-nightly-linux-amd64.tar.gz";
      hash = "sha256-e4DrqVYvkj446+cz/b/eQqrH/AlSGwn4mOs8dsmNGKU=";
    };
  };
}
