indent_style = "Block"
reorder_imports = false
tab_spaces = 2
max_width = 120
match_block_trailing_comma = true
imports_granularity = "Crate"

# Function
fn_call_width = 80
fn_params_layout = "Vertical"

