[package]
name = "ignis"
version = "0.1.0"
authors = ["Ignacio Perez <ignacio@feuer.me>"]
description = "Ignis self-hosted compiler source"
keywords = ["programming", "language", "compiler"]
license = "GPL-3.0-only"
repository = "https://github.com/Ignis-lang/ignis"

[ignis]
std = true
std_path = "std"
runtime_path = "std/runtime"

[aliases]
"@compiler" = "./ignis"

[build]
bin = true
source_dir = "ignis"
entry = "main.ign"
out_dir = "build/selfhost"
opt_level = 2
debug = false
target = "c"
cc = "gcc"
cflags = []
emit = []

[test]
fixtures = ["test_cases/e2e/ok", "test_cases/e2e/err"]
