name = "ignis"
version = "0.1.0"
authors = ["iperez"]
description = ""
keywords = []
license = "MIT"
repository = ""

[ignis]
std_path = "/home/iperez/dev/personal/Ignis/ignisc/std"
std = true

[build]
source_dir = "src"
main_file = ""
target = "C"
optimize = true
output_dir = "build"
