[package]
name = "ignis"
version = "0.1.0"
authors = []
description = "Ignis self-hosted compiler source"
keywords = []
license = "MIT"
repository = ""

[ignis]
std = true
std_path = "std"
runtime_path = "std/runtime"

[aliases]
"@compiler" = "./ignis"

[build]
bin = true
source_dir = "ignis"
entry = "main.ign"
out_dir = "build/selfhost"
opt_level = 0
debug = false
target = "c"
cc = "gcc"
cflags = []
emit = []
