use std::fmt::format;

use enums::data_type::DataType;
use intermediate_representation::analyzer_value::AnalyzerValue;
use token::token::Token;
use diagnostic_report::{DiagnosticReport, DiagnosticLevel};

#[derive(Debug, Clone)]
pub enum AnalyzerDiagnosticError {
  UndeclaredVariable(Token),
  InvalidUnaryOperatorForDataType(Token, AnalyzerValue),
  NotCallable(Token),
  InvalidNumberOfArguments(usize, usize, Token),
  AssingInvalidType(DataType, DataType, Token),
  InvalidArgumentType(AnalyzerValue, Token),
  MissingArgument(String, Token),
  InvalidComparison(AnalyzerValue, AnalyzerValue, Token),
  InvalidOperator(Token),
  InvalidUnaryOperator(Token),
  UndefinedVariable(Token),
  VariableAlreadyDefined(String, Token),
  InvalidAssignmentTarget(Token),
  InvalidReassignedVariable(Token),
  TypeMismatch(DataType, DataType, Token),
  TypeMismatchUnary(DataType, Token),
  CannotSubtract(AnalyzerValue, AnalyzerValue, Token),
  CannotMultiply(AnalyzerValue, AnalyzerValue, Token),
  CannotDivide(AnalyzerValue, AnalyzerValue, Token),
  CannotModulo(AnalyzerValue, AnalyzerValue, Token),
  FunctionAlreadyDefined(String, Token),
  ClassAlreadyDefined(Token),
  ArgumentTypeMismatch(DataType, DataType, Token),
  ImmutableVariableAsMutableParameter(String, String, Token),
  ReturnOutsideFunction(Token),
  NotIterable(Token),
  ArrayElementTypeMismatch(Token),
  ModuleNotFound(Token),
  ImportedFunctionIsNotExported(Token),
  BreakOutsideLoop(Token),
  ContinueOutsideLoop(Token),
  InvalidCondition(Token),
  PropertyOutsideClass(Token),
  PropertyAlreadyDefined(Token),
  MethodOutsideClass(Token),
  MethodAlreadyDefined(Token),
  UndefinedProperty(Token),
  NotAClass(Token),
  UndefinedClass(Token),
  UndefinedMethods(Token),
  ImmutableProperty(Token),
  PrivateProperty(Token),
  FunctionNotDefined(String, Token),
  VariableNeverUsed(Token),
  NotAnArray(Token),
  InvalidArrayIndex(Token),
  ThisOutsideOfClass(Token),
  ImportedClassIsNotExported(Token),
  InvalidVariableInitializer(Token),
  EnumAlreadyDefined(Token),
  EnumMemberTypeMismatch(Token),
}

#[derive(Debug, Clone)]
pub struct AnalyzerDiagnostic {
  pub error: AnalyzerDiagnosticError,
  pub token_line: Vec<Token>,
}

impl AnalyzerDiagnostic {
  pub fn new(
    error: AnalyzerDiagnosticError,
    token_line: Vec<Token>,
  ) -> Self {
    Self { error, token_line }
  }

  pub fn report_diagnostic(&self) -> DiagnosticReport {
    match &self.error {
      AnalyzerDiagnosticError::UndeclaredVariable(token) => DiagnosticReport::new(
        format!("Undeclared variable '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0001".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidUnaryOperatorForDataType(token, value) => DiagnosticReport::new(
        format!("Invalid unary operator '{}' for data type '{}'", token.span.literal, value),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0002".to_string(),
      ),
      AnalyzerDiagnosticError::NotCallable(token) => DiagnosticReport::new(
        format!("'{}' is not callable", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0003".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidNumberOfArguments(max, num, token) => DiagnosticReport::new(
        format!(
          "Function '{}': expected {} arguments, but got {} arguments",
          token.span.literal, max, num
        ),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0004".to_string(),
      ),
      AnalyzerDiagnosticError::AssingInvalidType(expected, target, token) => DiagnosticReport::new(
        format!("Cannot assign '{}' to '{}'", expected, target),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0005".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidArgumentType(value, token) => DiagnosticReport::new(
        format!("Invalid argument type '{}'", value),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0006".to_string(),
      ),
      AnalyzerDiagnosticError::MissingArgument(name, toke) => DiagnosticReport::new(
        format!("Missing argument '{}'", name),
        Box::new(toke.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0007".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidComparison(left, right, operator) => DiagnosticReport::new(
        format!("Invalid comparison between '{}' and '{}'", left, right),
        Box::new(operator.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0008".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidOperator(token) => DiagnosticReport::new(
        format!("Invalid operator '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0009".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidUnaryOperator(token) => DiagnosticReport::new(
        format!("Invalid unary operator '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0010".to_string(),
      ),
      AnalyzerDiagnosticError::UndefinedVariable(token) => DiagnosticReport::new(
        format!("Undefined variable '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0011".to_string(),
      ),
      AnalyzerDiagnosticError::VariableAlreadyDefined(name, token) => DiagnosticReport::new(
        format!("Variable '{}' already defined", name),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0012".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidAssignmentTarget(token) => DiagnosticReport::new(
        "Invalid assignment target".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0013".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidReassignedVariable(token) => DiagnosticReport::new(
        format!("Cannot reassign variable '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0014".to_string(),
      ),
      AnalyzerDiagnosticError::TypeMismatch(left, right, token) => DiagnosticReport::new(
        format!("Type mismatch between '{}' and '{}'", left, right),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0015".to_string(),
      ),
      AnalyzerDiagnosticError::TypeMismatchUnary(kind, token) => DiagnosticReport::new(
        format!("Type mismatch for unary operator '{}'", kind),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0016".to_string(),
      ),
      AnalyzerDiagnosticError::CannotSubtract(left_kind, right_kind, token) => DiagnosticReport::new(
        format!("Cannot subtract '{}' and '{}'", left_kind, right_kind),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0017".to_string(),
      ),
      AnalyzerDiagnosticError::CannotMultiply(left_kind, right_kind, token) => DiagnosticReport::new(
        format!("Cannot multiply '{}' and '{}'", left_kind, right_kind),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0018".to_string(),
      ),
      AnalyzerDiagnosticError::CannotDivide(left_kind, right_kind, token) => DiagnosticReport::new(
        format!("Cannot divide '{}' and '{}'", left_kind, right_kind),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0019".to_string(),
      ),
      AnalyzerDiagnosticError::CannotModulo(left_kind, right_kind, token) => DiagnosticReport::new(
        format!("Cannot modulo '{}' and '{}'", left_kind, right_kind),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0020".to_string(),
      ),
      AnalyzerDiagnosticError::FunctionAlreadyDefined(name, token) => DiagnosticReport::new(
        format!("Function '{}' already defined", name),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0021".to_string(),
      ),
      AnalyzerDiagnosticError::ClassAlreadyDefined(token) => DiagnosticReport::new(
        format!("Class '{}' already defined", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0022".to_string(),
      ),
      AnalyzerDiagnosticError::ArgumentTypeMismatch(expected, gived, token) => DiagnosticReport::new(
        format!("Expected argument type '{}', but got '{}'", expected, gived),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0023".to_string(),
      ),
      AnalyzerDiagnosticError::ImmutableVariableAsMutableParameter(parameter, var, token) => DiagnosticReport::new(
        format!("Cannot use immutable variable '{}' as mutable parameter '{}'", var, parameter),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0024".to_string(),
      ),
      AnalyzerDiagnosticError::ReturnOutsideFunction(token) => DiagnosticReport::new(
        "Return outside function".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0025".to_string(),
      ),
      AnalyzerDiagnosticError::NotIterable(token) => DiagnosticReport::new(
        format!("'{}' is not iterable", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0026".to_string(),
      ),
      AnalyzerDiagnosticError::ArrayElementTypeMismatch(token) => DiagnosticReport::new(
        "Array element type mismatch".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0027".to_string(),
      ),
      AnalyzerDiagnosticError::ModuleNotFound(token) => DiagnosticReport::new(
        format!("Module '{}' not found", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0028".to_string(),
      ),
      AnalyzerDiagnosticError::ImportedFunctionIsNotExported(token) => DiagnosticReport::new(
        format!("Imported function '{}' is not exported", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0029".to_string(),
      ),
      AnalyzerDiagnosticError::BreakOutsideLoop(token) => DiagnosticReport::new(
        "Break outside loop".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0030".to_string(),
      ),
      AnalyzerDiagnosticError::ContinueOutsideLoop(token) => DiagnosticReport::new(
        "Continue outside loop".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0031".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidCondition(token) => DiagnosticReport::new(
        "Invalid condition".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0032".to_string(),
      ),
      AnalyzerDiagnosticError::PropertyOutsideClass(token) => DiagnosticReport::new(
        format!("Property '{}' outside class", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0033".to_string(),
      ),
      AnalyzerDiagnosticError::PropertyAlreadyDefined(token) => DiagnosticReport::new(
        format!("Property '{}' already defined", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0034".to_string(),
      ),
      AnalyzerDiagnosticError::MethodOutsideClass(token) => DiagnosticReport::new(
        format!("Method '{}' outside class", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0035".to_string(),
      ),
      AnalyzerDiagnosticError::MethodAlreadyDefined(token) => DiagnosticReport::new(
        format!("Method '{}' already defined", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0036".to_string(),
      ),
      AnalyzerDiagnosticError::UndefinedProperty(token) => DiagnosticReport::new(
        format!("Undefined property '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0037".to_string(),
      ),
      AnalyzerDiagnosticError::NotAClass(token) => DiagnosticReport::new(
        format!("'{}' is not a class", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0038".to_string(),
      ),
      AnalyzerDiagnosticError::UndefinedClass(token) => DiagnosticReport::new(
        format!("Undefined class '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0039".to_string(),
      ),
      AnalyzerDiagnosticError::UndefinedMethods(token) => DiagnosticReport::new(
        "Undefined methods".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0040".to_string(),
      ),
      AnalyzerDiagnosticError::ImmutableProperty(token) => DiagnosticReport::new(
        format!("The property '{}' is immutable", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0041".to_string(),
      ),
      AnalyzerDiagnosticError::PrivateProperty(token) => DiagnosticReport::new(
        format!("The property '{}' is private", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0042".to_string(),
      ),
      AnalyzerDiagnosticError::VariableNeverUsed(token) => DiagnosticReport::new(
        "Variable never used".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Warning,
        None,
        "IA0043".to_string(),
      ),
      AnalyzerDiagnosticError::FunctionNotDefined(name, token) => DiagnosticReport::new(
        format!("Function '{}' not defined", name),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0044".to_string(),
      ),
      AnalyzerDiagnosticError::NotAnArray(token) => DiagnosticReport::new(
        "Not an array".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0045".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidArrayIndex(token) => DiagnosticReport::new(
        "Invalid array index".to_string(),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0046".to_string(),
      ),
      AnalyzerDiagnosticError::ThisOutsideOfClass(toke) => DiagnosticReport::new(
        "Invalid 'this' outside of class".to_string(),
        Box::new(toke.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0047".to_string(),
      ),
      AnalyzerDiagnosticError::ImportedClassIsNotExported(token) => DiagnosticReport::new(
        format!("Imported class '{}' is not exported", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0048".to_string(),
      ),
      AnalyzerDiagnosticError::InvalidVariableInitializer(token) => DiagnosticReport::new(
        format!("Invalid variable initializer '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0049".to_string(),
      ),
      AnalyzerDiagnosticError::EnumAlreadyDefined(token) => DiagnosticReport::new(
        format!("Enum '{}' already defined", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0050".to_string(),
      ),
      AnalyzerDiagnosticError::EnumMemberTypeMismatch(token) => DiagnosticReport::new(
        format!("Enum member type mismatch '{}'", token.span.literal),
        Box::new(token.clone()),
        self.token_line.clone(),
        DiagnosticLevel::Error,
        None,
        "IA0051".to_string(),
      ),
    }
  }
}
