[package]
name = "qbe_lane"

[ignis]
std = true
std_path = "../../std"

[aliases]
"@compiler" = "../../ignis"

[build]
bin = true
source_dir = ".."
entry = "qbe_lane.ign"
out_dir = "../../build/qbe-lane"
target = "c"
